create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('goreng', 'kukus')),
  price integer not null default 0,
  stock integer not null default 0,
  image text,
  description text,
  badge text,
  specs jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
using (true);

insert into storage.buckets (id, name, public)
values ('katalog-gorengan', 'katalog-gorengan', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read katalog-gorengan files" on storage.objects;
create policy "Public can read katalog-gorengan files"
on storage.objects
for select
using (bucket_id = 'katalog-gorengan');
